line-length = 100
target-version = "py311"

[lint]
select = [
  "E",
  "F",
  "I",
  "N",
  "UP",
  "B",
  "S",
  "A",
  "PL",
  "RUF",
]
ignore = [
  "S101",  # Allow asserts in tests during scaffold phase
]

[format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"
